name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:6.0
        ports:
          - 27017:27017
    steps:
    - uses: actions/checkout@v4
    
    # 前端构建
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - run: npm ci --prefix client
    
    # 后端环境
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - run: pip install poetry
    - run: poetry install --directory server
    
    # 运行测试
    - name: Run Tests
      env:
        MONGO_URI: mongodb://localhost:27017/test_db
        OPENAI_API_KEY: ${{ secrets.OPENAI_KEY }}
      run: |
        pytest tests/ -v
        npm test --prefix client